//movies project
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";

//ECOMMERCE PROJECT
export const ADD_PRODUCT="ADD_PRODUCT"
export const EDIT_PRODUCT="EDIT_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const DISPONIBLE_PRODUCT="DISPONIBLE_PRODUCT"

